### ISSUE TITLE
Build error with performance-time tests due to snippet-lib

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-tool#3]
The performance-time snippets does not have snippet-lib as they don't need it.

However, TestSuiteGenererator creates an ant file for all snippet projects, which have the following lines:

```
                <fileset dir="snippet-lib">
                    <include name="**/*.jar" />
                </fileset>
```

Thus the performance-time tests are not compiling, these lines had to be removed first.

**Comment by LajosCseppento** [comment]
Update c12b34c

**Comment by LajosCseppento** [comment]
Quick fix:

``` bash
cd sette-results
find . -maxdepth 1 -type d -printf "%P\n" | grep "^sette" | while read dir; do mkdir -p "$dir/snippet-lib"; done
```

**Comment by micskeiz** [comment]
Commit fixes the problem.

**Comment by micskeiz** [comment]
This is still a problem, but now for tool runner. Maybe:
- create the snippet-lib in performance time, and also in the script creating that project
- or check each tool runner's build.xml and update that this folder is not necessary

**Comment by micskeiz** [comment]
Fixed already with a commit in the sette-snippets repo.
