### ISSUE TITLE
Parser: new, unhandled error for EvoSuite (Unprivileged thread cannot add a privileged thread)

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-tool#6]
EvoSuiteParser could not parse the following lines in the std error log:

```
[MASTER] 07:27:41.484 [logback-2] ERROR ClientNodeImpl - Error when connecting to master via RMI
java.lang.SecurityException: Unprivileged thread "main" cannot add a privileged thread: failed to add "Statistics sender in client process"
```

No tests were generated.

SETTE parser log:
[evosuite_run-02-60sec_3_parser.log.txt](https://github.com/SETTE-Testing/sette-tool/files/178000/evosuite_run-02-60sec_3_parser.log.txt)

EvoSuite output:
[O3b_Interface_guessImpossible.out.txt](https://github.com/SETTE-Testing/sette-tool/files/177990/O3b_Interface_guessImpossible.out.txt)
[O3b_Interface_guessImpossible.err.txt](https://github.com/SETTE-Testing/sette-tool/files/177992/O3b_Interface_guessImpossible.err.txt)
[O3b_Interface_guessImpossible.info.txt](https://github.com/SETTE-Testing/sette-tool/files/177991/O3b_Interface_guessImpossible.info.txt)

**Comment by LajosCseppento** [comment]
Seems tool related problem, but I was unable to reproduce. Handle as EX?

**Comment by micskeiz** [comment]
It is rare, only 1 from the 5000+ executions.

It is not a clear EX, as the problem is not with the snippets, probably some timing or resource issues in the environment. And EvoSuite handled the internal exception, just test generation was not even started.

Maybe this snippet should be rerun?
