### ISSUE TITLE
Parser: new, unhandled error for EvoSuite (RemoteException occurred in server thread)

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-tool#7]
EvoSuiteParser could not handle the following lines in the error output:

```
[MASTER] 16:36:21.542 [logback-2] ERROR ClientNodeImpl - Cannot inform master of change of state
java.rmi.ServerException: RemoteException occurred in server thread; nested exception is: 
    java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
    java.io.OptionalDataException
```

Tests were successfully generated:
[B2d_Nonlinear_quadraticInt_quadraticInt_Test.java.txt](https://github.com/SETTE-Testing/sette-tool/files/178040/B2d_Nonlinear_quadraticInt_quadraticInt_Test.java.txt)

SETTE log file:
[evosuite_run-06-60sec_3_parser.log.txt](https://github.com/SETTE-Testing/sette-tool/files/178024/evosuite_run-06-60sec_3_parser.log.txt)

EvoSuite output:
[B2d_Nonlinear_quadraticInt.info.txt](https://github.com/SETTE-Testing/sette-tool/files/178028/B2d_Nonlinear_quadraticInt.info.txt)
[B2d_Nonlinear_quadraticInt.out.txt](https://github.com/SETTE-Testing/sette-tool/files/178029/B2d_Nonlinear_quadraticInt.out.txt)
[B2d_Nonlinear_quadraticInt.err.txt](https://github.com/SETTE-Testing/sette-tool/files/178030/B2d_Nonlinear_quadraticInt.err.txt)

**Comment by LajosCseppento** [comment]
In order to avoid errors like this in the future, can we handle all cases when a test code is generated as NC / C?

**Comment by micskeiz** [comment]
Yes, if a test code is generated, then it is NC/C and all the errors can be threated as handled by the tool.
