### ISSUE TITLE
Parser: new, unhandled error for EvoSuite (ERROR JUnitAnalyzer - Compilation failed on compilation units)

### ISSUE THREAD

**Issue by micskeiz** [SETTE-Testing/sette-tool#8]
EvoSuiteParser could not parse the following lines in EvoSuite error output:

```
[MASTER] 00:26:14.732 [logback-2] ERROR JUnitAnalyzer - Compilation failed on compilation units
[MASTER] 00:26:14.732 [logback-2] ERROR JUnitAnalyzer - Classpath:
[MASTER] 00:26:14.732 [logback-2] ERROR JUnitAnalyzer - evosuiteCP:
[MASTER] 00:26:14.737 [logback-2] ERROR JUnitAnalyzer - Diagnostic: method test5() is already defined in class
[MASTER] 00:26:14.737 [logback-2] ERROR JUnitAnalyzer - Diagnostic: method test5() is already defined in class
...
```

NOTE: this line can also appear after the following (if there was only 1 compilation error in the file):

```
ERROR JUnitAnalyzer - 1 test cases failed
```

(This single line is handled in EvoSuiteParser, but the "Compilation failed..." and the others are not.)

Tests were generated (EvoSuite removed the problematic, repeated tests methods in the final test file, they were empty methods):
[O1_Simple_guessImpossibleResultAndOperationCount_guessImpossibleResultAndOperationCount_Test.java.txt](https://github.com/SETTE-Testing/sette-tool/files/178059/O1_Simple_guessImpossibleResultAndOperationCount_guessImpossibleResultAndOperationCount_Test.java.txt)

SETTE output:
[evosuite_run-09-60sec_3_parser.log.txt](https://github.com/SETTE-Testing/sette-tool/files/178061/evosuite_run-09-60sec_3_parser.log.txt)

EvoSuite output:
[O1_Simple_guessImpossibleResultAndOperationCount.out.txt](https://github.com/SETTE-Testing/sette-tool/files/178067/O1_Simple_guessImpossibleResultAndOperationCount.out.txt)
[O1_Simple_guessImpossibleResultAndOperationCount.err.txt](https://github.com/SETTE-Testing/sette-tool/files/178069/O1_Simple_guessImpossibleResultAndOperationCount.err.txt)
[O1_Simple_guessImpossibleResultAndOperationCount.info.txt](https://github.com/SETTE-Testing/sette-tool/files/178068/O1_Simple_guessImpossibleResultAndOperationCount.info.txt)

**Comment by LajosCseppento** [comment]
Same solution as #7 ?

**Comment by micskeiz** [comment]
Yes,I think the same solution would be good.
